[versions]
agp = "8.13.2"
android-compileSdk = "36"
android-minSdk = "24"
android-targetSdk = "36"
androidx-activity = "1.12.2"
androidx-appcompat = "1.7.1"
androidx-core = "1.17.0"
androidx-espresso = "3.7.0"
androidx-lifecycle = "2.9.6"
androidx-testExt = "1.3.0"
composeMultiplatform = "1.7.1"
junit = "4.13.2"
kotlin = "2.1.0"
redwood = "0.18.0"
zipline = "1.24.0"
okhttp = "4.12.0"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-testJunit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
junit = { module = "junit:junit", version.ref = "junit" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-testExt-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-testExt" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-espresso" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-lifecycle-viewmodelCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtimeCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
redwood-schema = { module = "app.cash.redwood:redwood-schema", version.ref = "redwood" }
redwood-compose = { module = "app.cash.redwood:redwood-compose", version.ref = "redwood" }
redwood-widget = { module = "app.cash.redwood:redwood-widget", version.ref = "redwood" }
redwood-treehouse = { module = "app.cash.redwood:redwood-treehouse", version.ref = "redwood" }
redwoodProtocol = { module = "app.cash.redwood:redwood-protocol", version.ref = "redwood" }
redwood-protocol-host = { module = "app.cash.redwood:redwood-protocol-host", version.ref = "redwood" }
redwood-protocol-guest = { module = "app.cash.redwood:redwood-protocol-guest", version.ref = "redwood" }
redwood-treehouse-host = { module = "app.cash.redwood:redwood-treehouse-host", version.ref = "redwood" }
redwood-treehouse-host-composeui = { module = "app.cash.redwood:redwood-treehouse-host-composeui", version.ref = "redwood" }
redwood-treehouse-guest = { module = "app.cash.redwood:redwood-treehouse-guest", version.ref = "redwood" }
zipline = { module = "app.cash.zipline:zipline", version.ref = "zipline" }
zipline-loader = { module = "app.cash.zipline:zipline-loader", version.ref = "zipline" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
android-kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
redwood = { id = "app.cash.redwood.schema", version.ref = "redwood" }
redwood-generator-compose = { id = "app.cash.redwood.generator.compose", version.ref = "redwood" }
redwood-generator-widget = { id = "app.cash.redwood.generator.widget", version.ref = "redwood" }
redwood-generator-protocol-host = { id = "app.cash.redwood.generator.protocol.host", version.ref = "redwood" }
redwood-generator-protocol-guest = { id = "app.cash.redwood.generator.protocol.guest", version.ref = "redwood" }
# redwood-generator-protocol-guest = { id = "app.cash.redwood.generator.protocol.guest", version.ref = "redwood" } # Optional for guest
zipline = { id = "app.cash.zipline", version.ref = "zipline" }